// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

#ifndef PROTOBUF_login_2eproto__INCLUDED
#define PROTOBUF_login_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_login_2eproto();
void protobuf_AssignDesc_login_2eproto();
void protobuf_ShutdownFile_login_2eproto();

class CMsgPlayerLoginRequest;
class CMsgPlayerLoginResponse;

enum LoginOpcode {
  ID_C2S_PLAYER_LOGIN_REQUEST = 65537,
  ID_S2C_PLAYER_LOGIN_RESPONSE = 65538
};
bool LoginOpcode_IsValid(int value);
const LoginOpcode LoginOpcode_MIN = ID_C2S_PLAYER_LOGIN_REQUEST;
const LoginOpcode LoginOpcode_MAX = ID_S2C_PLAYER_LOGIN_RESPONSE;
const int LoginOpcode_ARRAYSIZE = LoginOpcode_MAX + 1;

const ::google::protobuf::EnumDescriptor* LoginOpcode_descriptor();
inline const ::std::string& LoginOpcode_Name(LoginOpcode value) {
  return ::google::protobuf::internal::NameOfEnum(
    LoginOpcode_descriptor(), value);
}
inline bool LoginOpcode_Parse(
    const ::std::string& name, LoginOpcode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LoginOpcode>(
    LoginOpcode_descriptor(), name, value);
}
// ===================================================================

class CMsgPlayerLoginRequest : public ::google::protobuf::Message {
 public:
  CMsgPlayerLoginRequest();
  virtual ~CMsgPlayerLoginRequest();

  CMsgPlayerLoginRequest(const CMsgPlayerLoginRequest& from);

  inline CMsgPlayerLoginRequest& operator=(const CMsgPlayerLoginRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgPlayerLoginRequest& default_instance();

  void Swap(CMsgPlayerLoginRequest* other);

  // implements Message ----------------------------------------------

  CMsgPlayerLoginRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CMsgPlayerLoginRequest& from);
  void MergeFrom(const CMsgPlayerLoginRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string username = 1;
  inline bool has_username() const;
  inline void clear_username();
  static const int kUsernameFieldNumber = 1;
  inline const ::std::string& username() const;
  inline void set_username(const ::std::string& value);
  inline void set_username(const char* value);
  inline void set_username(const char* value, size_t size);
  inline ::std::string* mutable_username();
  inline ::std::string* release_username();
  inline void set_allocated_username(::std::string* username);

  // required string password = 2;
  inline bool has_password() const;
  inline void clear_password();
  static const int kPasswordFieldNumber = 2;
  inline const ::std::string& password() const;
  inline void set_password(const ::std::string& value);
  inline void set_password(const char* value);
  inline void set_password(const char* value, size_t size);
  inline ::std::string* mutable_password();
  inline ::std::string* release_password();
  inline void set_allocated_password(::std::string* password);

  // @@protoc_insertion_point(class_scope:CMsgPlayerLoginRequest)
 private:
  inline void set_has_username();
  inline void clear_has_username();
  inline void set_has_password();
  inline void clear_has_password();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* username_;
  ::std::string* password_;
  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static CMsgPlayerLoginRequest* default_instance_;
};
// -------------------------------------------------------------------

class CMsgPlayerLoginResponse : public ::google::protobuf::Message {
 public:
  CMsgPlayerLoginResponse();
  virtual ~CMsgPlayerLoginResponse();

  CMsgPlayerLoginResponse(const CMsgPlayerLoginResponse& from);

  inline CMsgPlayerLoginResponse& operator=(const CMsgPlayerLoginResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgPlayerLoginResponse& default_instance();

  void Swap(CMsgPlayerLoginResponse* other);

  // implements Message ----------------------------------------------

  CMsgPlayerLoginResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CMsgPlayerLoginResponse& from);
  void MergeFrom(const CMsgPlayerLoginResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string entityId = 1;
  inline bool has_entityid() const;
  inline void clear_entityid();
  static const int kEntityIdFieldNumber = 1;
  inline const ::std::string& entityid() const;
  inline void set_entityid(const ::std::string& value);
  inline void set_entityid(const char* value);
  inline void set_entityid(const char* value, size_t size);
  inline ::std::string* mutable_entityid();
  inline ::std::string* release_entityid();
  inline void set_allocated_entityid(::std::string* entityid);

  // @@protoc_insertion_point(class_scope:CMsgPlayerLoginResponse)
 private:
  inline void set_has_entityid();
  inline void clear_has_entityid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* entityid_;
  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static CMsgPlayerLoginResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// CMsgPlayerLoginRequest

// required string username = 1;
inline bool CMsgPlayerLoginRequest::has_username() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgPlayerLoginRequest::set_has_username() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgPlayerLoginRequest::clear_has_username() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgPlayerLoginRequest::clear_username() {
  if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_->clear();
  }
  clear_has_username();
}
inline const ::std::string& CMsgPlayerLoginRequest::username() const {
  // @@protoc_insertion_point(field_get:CMsgPlayerLoginRequest.username)
  return *username_;
}
inline void CMsgPlayerLoginRequest::set_username(const ::std::string& value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(value);
  // @@protoc_insertion_point(field_set:CMsgPlayerLoginRequest.username)
}
inline void CMsgPlayerLoginRequest::set_username(const char* value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(value);
  // @@protoc_insertion_point(field_set_char:CMsgPlayerLoginRequest.username)
}
inline void CMsgPlayerLoginRequest::set_username(const char* value, size_t size) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:CMsgPlayerLoginRequest.username)
}
inline ::std::string* CMsgPlayerLoginRequest::mutable_username() {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:CMsgPlayerLoginRequest.username)
  return username_;
}
inline ::std::string* CMsgPlayerLoginRequest::release_username() {
  clear_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = username_;
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void CMsgPlayerLoginRequest::set_allocated_username(::std::string* username) {
  if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete username_;
  }
  if (username) {
    set_has_username();
    username_ = username;
  } else {
    clear_has_username();
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:CMsgPlayerLoginRequest.username)
}

// required string password = 2;
inline bool CMsgPlayerLoginRequest::has_password() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgPlayerLoginRequest::set_has_password() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgPlayerLoginRequest::clear_has_password() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgPlayerLoginRequest::clear_password() {
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_->clear();
  }
  clear_has_password();
}
inline const ::std::string& CMsgPlayerLoginRequest::password() const {
  // @@protoc_insertion_point(field_get:CMsgPlayerLoginRequest.password)
  return *password_;
}
inline void CMsgPlayerLoginRequest::set_password(const ::std::string& value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(value);
  // @@protoc_insertion_point(field_set:CMsgPlayerLoginRequest.password)
}
inline void CMsgPlayerLoginRequest::set_password(const char* value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(value);
  // @@protoc_insertion_point(field_set_char:CMsgPlayerLoginRequest.password)
}
inline void CMsgPlayerLoginRequest::set_password(const char* value, size_t size) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:CMsgPlayerLoginRequest.password)
}
inline ::std::string* CMsgPlayerLoginRequest::mutable_password() {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:CMsgPlayerLoginRequest.password)
  return password_;
}
inline ::std::string* CMsgPlayerLoginRequest::release_password() {
  clear_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = password_;
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void CMsgPlayerLoginRequest::set_allocated_password(::std::string* password) {
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete password_;
  }
  if (password) {
    set_has_password();
    password_ = password;
  } else {
    clear_has_password();
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:CMsgPlayerLoginRequest.password)
}

// -------------------------------------------------------------------

// CMsgPlayerLoginResponse

// required string entityId = 1;
inline bool CMsgPlayerLoginResponse::has_entityid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgPlayerLoginResponse::set_has_entityid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgPlayerLoginResponse::clear_has_entityid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgPlayerLoginResponse::clear_entityid() {
  if (entityid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    entityid_->clear();
  }
  clear_has_entityid();
}
inline const ::std::string& CMsgPlayerLoginResponse::entityid() const {
  // @@protoc_insertion_point(field_get:CMsgPlayerLoginResponse.entityId)
  return *entityid_;
}
inline void CMsgPlayerLoginResponse::set_entityid(const ::std::string& value) {
  set_has_entityid();
  if (entityid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    entityid_ = new ::std::string;
  }
  entityid_->assign(value);
  // @@protoc_insertion_point(field_set:CMsgPlayerLoginResponse.entityId)
}
inline void CMsgPlayerLoginResponse::set_entityid(const char* value) {
  set_has_entityid();
  if (entityid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    entityid_ = new ::std::string;
  }
  entityid_->assign(value);
  // @@protoc_insertion_point(field_set_char:CMsgPlayerLoginResponse.entityId)
}
inline void CMsgPlayerLoginResponse::set_entityid(const char* value, size_t size) {
  set_has_entityid();
  if (entityid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    entityid_ = new ::std::string;
  }
  entityid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:CMsgPlayerLoginResponse.entityId)
}
inline ::std::string* CMsgPlayerLoginResponse::mutable_entityid() {
  set_has_entityid();
  if (entityid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    entityid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:CMsgPlayerLoginResponse.entityId)
  return entityid_;
}
inline ::std::string* CMsgPlayerLoginResponse::release_entityid() {
  clear_has_entityid();
  if (entityid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = entityid_;
    entityid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void CMsgPlayerLoginResponse::set_allocated_entityid(::std::string* entityid) {
  if (entityid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete entityid_;
  }
  if (entityid) {
    set_has_entityid();
    entityid_ = entityid;
  } else {
    clear_has_entityid();
    entityid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:CMsgPlayerLoginResponse.entityId)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::LoginOpcode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::LoginOpcode>() {
  return ::LoginOpcode_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_login_2eproto__INCLUDED
