// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "module.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* ModuleID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_module_2eproto() {
  protobuf_AddDesc_module_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "module.proto");
  GOOGLE_CHECK(file != NULL);
  ModuleID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_module_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_module_2eproto() {
}

void protobuf_AddDesc_module_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014module.proto*\034\n\010ModuleID\022\020\n\014MODULE_LOG"
    "IN\020\001", 44);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "module.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_module_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_module_2eproto {
  StaticDescriptorInitializer_module_2eproto() {
    protobuf_AddDesc_module_2eproto();
  }
} static_descriptor_initializer_module_2eproto_;
const ::google::protobuf::EnumDescriptor* ModuleID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ModuleID_descriptor_;
}
bool ModuleID_IsValid(int value) {
  switch(value) {
    case 1:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
