// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

#ifndef PROTOBUF_module_2eproto__INCLUDED
#define PROTOBUF_module_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_module_2eproto();
void protobuf_AssignDesc_module_2eproto();
void protobuf_ShutdownFile_module_2eproto();


enum ModuleID {
  MODULE_LOGIN = 1
};
bool ModuleID_IsValid(int value);
const ModuleID ModuleID_MIN = MODULE_LOGIN;
const ModuleID ModuleID_MAX = MODULE_LOGIN;
const int ModuleID_ARRAYSIZE = ModuleID_MAX + 1;

const ::google::protobuf::EnumDescriptor* ModuleID_descriptor();
inline const ::std::string& ModuleID_Name(ModuleID value) {
  return ::google::protobuf::internal::NameOfEnum(
    ModuleID_descriptor(), value);
}
inline bool ModuleID_Parse(
    const ::std::string& name, ModuleID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ModuleID>(
    ModuleID_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::ModuleID> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ModuleID>() {
  return ::ModuleID_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_module_2eproto__INCLUDED
